#define BOOST_TEST_MODULE boost_test_macro_overview
#include <boost/test/included/unit_test.hpp>
#include <string>
#include "../../functions.hpp"

namespace tt = boost::test_tools;

BOOST_AUTO_TEST_CASE( test_no_1){

    BOOST_TEST(levenshtein("text", "test") == 1);
    BOOST_TEST(levenshtein("PLAIN", "PLAN") == 1);
    BOOST_TEST(levenshtein("TREE", "THREE") == 1);
    BOOST_TEST(levenshtein("WOMAN", "WOMEN") == 1);
    BOOST_TEST(levenshtein("KITTEN", "SITTING") == 3);
    BOOST_TEST(levenshtein("YPOEHOHRIWUBXMNHZF", "YCPOEHORIDUBXNHZF") == 4); 
}

BOOST_AUTO_TEST_CASE( test_no_2){
    
    BOOST_TEST(levenshtein("NWUTONMUZQZGEZKMCXRATLGLPOOOOBS", "NWUTNUZFQZGEZKXRTLGLIOODLOOBSM") == 10);
    BOOST_TEST(levenshtein("RMNARPSTQFBKJWJUNTIBAMIPXCTJPQB", "RJMNCARZCSTQFBKJWJUNXTIBAMGIPXTCJPQB") == 8);
    BOOST_TEST(levenshtein("JMFUNHRMDTBAKVGTOKCKIDYW", "MUNMRMHBABVGTOLKCKDYK") == 9);
    BOOST_TEST(levenshtein("CZKJWIHEBRBNSQZUZZSDAVHNUSBGA", "DEZKJWICEBBNSQZZUNZZSDAGVHNSBVAI") == 10);
    BOOST_TEST(levenshtein("LBFTMWAECUGPUJLRAQJJEJN", "SLBXLTMWLAENUGPKLRCQAJBJENN") == 11);
    BOOST_TEST(levenshtein("EKZZQSENXHEDOFZAPBOPRVNAQPKWS", "IEKGJQSZRENXHEDOFEPBKFPRVRIAPKWS") == 12);
    BOOST_TEST(levenshtein("TYYBDXBWLACBNLBSXGLEMI", "TYEYBDXBWLACBNLZXXGULEMI") == 4);
    BOOST_TEST(levenshtein("ZBUFULJZAVIJDCUKZRDMITHZYBBHP", "GBUFULJZVJDCUKZRDMITHZYBBVHP") == 4);
}